# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.10.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from hindsight_client_api.models.curation_inventory import CurationInventory
from hindsight_client_api.models.maintenance_debt import MaintenanceDebt
from typing import Optional, Set
from typing_extensions import Self

class CurationReceipt(BaseModel):
    """
    CurationReceipt
    """ # noqa: E501
    protocol: Optional[StrictStr] = 'raw-curation-v2'
    bank_id: StrictStr
    batch_id: Annotated[str, Field(strict=True)] = Field(description="Unique batch ID; the exact case-sensitive value 'preview' is reserved for the preview route")
    manifest_revision: Annotated[str, Field(strict=True)]
    receipt_revision: Annotated[str, Field(strict=True)]
    status: StrictStr
    inventory: CurationInventory
    maintenance_debt: MaintenanceDebt
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["protocol", "bank_id", "batch_id", "manifest_revision", "receipt_revision", "status", "inventory", "maintenance_debt"]

    @field_validator('batch_id')
    def batch_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}$/")
        return value

    @field_validator('manifest_revision')
    def manifest_revision_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{64}$/")
        return value

    @field_validator('receipt_revision')
    def receipt_revision_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[0-9a-f]{64}$", value):
            raise ValueError(r"must validate the regular expression /^[0-9a-f]{64}$/")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['applied', 'reverted']):
            raise ValueError("must be one of enum values ('applied', 'reverted')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CurationReceipt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of inventory
        if self.inventory:
            _dict['inventory'] = self.inventory.to_dict()
        # override the default output from pydantic by calling `to_dict()` of maintenance_debt
        if self.maintenance_debt:
            _dict['maintenance_debt'] = self.maintenance_debt.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CurationReceipt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "protocol": obj.get("protocol") if obj.get("protocol") is not None else 'raw-curation-v2',
            "bank_id": obj.get("bank_id"),
            "batch_id": obj.get("batch_id"),
            "manifest_revision": obj.get("manifest_revision"),
            "receipt_revision": obj.get("receipt_revision"),
            "status": obj.get("status"),
            "inventory": CurationInventory.from_dict(obj["inventory"]) if obj.get("inventory") is not None else None,
            "maintenance_debt": MaintenanceDebt.from_dict(obj["maintenance_debt"]) if obj.get("maintenance_debt") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


