# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.10.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CurationFactType(str, Enum):
    """
    CurationFactType
    """

    """
    allowed enum values
    """
    WORLD = 'world'
    EXPERIENCE = 'experience'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CurationFactType from a JSON string"""
        return cls(json.loads(json_str))


