# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.ocr_quality_reason import OcrQualityReason
from typing import Optional, Set
from typing_extensions import Self

class FileConvertRetainOperationDetails(BaseModel):
    """
    A deterministic terminal outcome from a file conversion operation.
    """ # noqa: E501
    operation_type: Optional[StrictStr] = Field(default='file_convert_retain', description="Discriminator: which operation type this detail describes.")
    failure_class: StrictStr = Field(description="Stable failure class callers may use to decide whether the source artifact is retryable.")
    failure_reason: OcrQualityReason = Field(description="The OCR quality gate that rejected the converted image text.")
    __properties: ClassVar[List[str]] = ["operation_type", "failure_class", "failure_reason"]

    @field_validator('operation_type')
    def operation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['file_convert_retain']):
            raise ValueError("must be one of enum values ('file_convert_retain')")
        return value

    @field_validator('failure_class')
    def failure_class_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['low_quality_ocr']):
            raise ValueError("must be one of enum values ('low_quality_ocr')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileConvertRetainOperationDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileConvertRetainOperationDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "operation_type": obj.get("operation_type") if obj.get("operation_type") is not None else 'file_convert_retain',
            "failure_class": obj.get("failure_class"),
            "failure_reason": obj.get("failure_reason")
        })
        return _obj


