# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OcrQualityReason(str, Enum):
    """
    Stable reason codes for rejected OCR.
    """

    """
    allowed enum values
    """
    REFUSAL_OR_NO_TEXT_RESPONSE = 'refusal_or_no_text_response'
    NO_MEANINGFUL_TEXT = 'no_meaningful_text'
    EXCESSIVE_UNCERTAINTY = 'excessive_uncertainty'
    EXCESSIVE_REPETITION = 'excessive_repetition'
    UI_CHROME_ONLY = 'ui_chrome_only'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OcrQualityReason from a JSON string"""
        return cls(json.loads(json_str))


