# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.10.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator, model_validator
from typing import Any, List, Optional
from hindsight_client_api.models.file_convert_retain_operation_details import FileConvertRetainOperationDetails
from hindsight_client_api.models.refresh_mental_model_operation_details import RefreshMentalModelOperationDetails
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

OPERATIONRESPONSEDETAILS_ONE_OF_SCHEMAS = ["FileConvertRetainOperationDetails", "RefreshMentalModelOperationDetails"]

class OperationResponseDetails(BaseModel):
    """
    OperationResponseDetails
    """
    # data type: RefreshMentalModelOperationDetails
    oneof_schema_1_validator: Optional[RefreshMentalModelOperationDetails] = None
    # data type: FileConvertRetainOperationDetails
    oneof_schema_2_validator: Optional[FileConvertRetainOperationDetails] = None
    actual_instance: Optional[Union[FileConvertRetainOperationDetails, RefreshMentalModelOperationDetails]] = None
    one_of_schemas: Set[str] = { "FileConvertRetainOperationDetails", "RefreshMentalModelOperationDetails" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    @model_validator(mode='before')
    @classmethod
    def validate_wire_details(cls, value: Any) -> Any:
        # Generated oneOf wrappers otherwise ignore raw wire fields when nested,
        # and trial-decode JSON null as a successful match for EVERY variant.
        if value is None:
            return {'actual_instance': None}
        if isinstance(value, dict) and 'actual_instance' not in value:
            operation_type = value.get('operation_type')
            variants = {
                'file_convert_retain': FileConvertRetainOperationDetails,
                'refresh_mental_model': RefreshMentalModelOperationDetails,
            }
            if not isinstance(operation_type, str) or operation_type not in variants:
                raise ValueError(f'Unknown operation details type: {operation_type!r}')
            return {'actual_instance': variants[operation_type].model_validate(value)}
        return value

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        if v is None:
            return v

        instance = OperationResponseDetails.model_construct()
        error_messages = []
        match = 0
        # validate data type: RefreshMentalModelOperationDetails
        if not isinstance(v, RefreshMentalModelOperationDetails):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RefreshMentalModelOperationDetails`")
        else:
            match += 1
        # validate data type: FileConvertRetainOperationDetails
        if not isinstance(v, FileConvertRetainOperationDetails):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FileConvertRetainOperationDetails`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in OperationResponseDetails with oneOf schemas: FileConvertRetainOperationDetails, RefreshMentalModelOperationDetails. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in OperationResponseDetails with oneOf schemas: FileConvertRetainOperationDetails, RefreshMentalModelOperationDetails. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Optional[Union[str, Dict[str, Any]]]) -> Self:
        return cls.model_validate(obj)

    @classmethod
    def from_json(cls, json_str: Optional[str]) -> Self:
        """Decode null once, otherwise select by the wire discriminator."""
        return cls.from_dict(None if json_str is None else json.loads(json_str))

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FileConvertRetainOperationDetails, RefreshMentalModelOperationDetails]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


