/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the CurationInventory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationInventory{}

// CurationInventory struct for CurationInventory
type CurationInventory struct {
	Targets int32 `json:"targets"`
	Observations int32 `json:"observations"`
	Peers int32 `json:"peers"`
	Entities int32 `json:"entities"`
	Links int32 `json:"links"`
	HistoryRows int32 `json:"history_rows"`
	SnapshotBytes int32 `json:"snapshot_bytes"`
	SourceBytes int32 `json:"source_bytes"`
	AdditionalProperties map[string]interface{}
}

type _CurationInventory CurationInventory

// NewCurationInventory instantiates a new CurationInventory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationInventory(targets int32, observations int32, peers int32, entities int32, links int32, historyRows int32, snapshotBytes int32, sourceBytes int32) *CurationInventory {
	this := CurationInventory{}
	this.Targets = targets
	this.Observations = observations
	this.Peers = peers
	this.Entities = entities
	this.Links = links
	this.HistoryRows = historyRows
	this.SnapshotBytes = snapshotBytes
	this.SourceBytes = sourceBytes
	return &this
}

// NewCurationInventoryWithDefaults instantiates a new CurationInventory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationInventoryWithDefaults() *CurationInventory {
	this := CurationInventory{}
	return &this
}

// GetTargets returns the Targets field value
func (o *CurationInventory) GetTargets() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value
// and a boolean to check if the value has been set.
func (o *CurationInventory) GetTargetsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Targets, true
}

// SetTargets sets field value
func (o *CurationInventory) SetTargets(v int32) {
	o.Targets = v
}

// GetObservations returns the Observations field value
func (o *CurationInventory) GetObservations() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Observations
}

// GetObservationsOk returns a tuple with the Observations field value
// and a boolean to check if the value has been set.
func (o *CurationInventory) GetObservationsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Observations, true
}

// SetObservations sets field value
func (o *CurationInventory) SetObservations(v int32) {
	o.Observations = v
}

// GetPeers returns the Peers field value
func (o *CurationInventory) GetPeers() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Peers
}

// GetPeersOk returns a tuple with the Peers field value
// and a boolean to check if the value has been set.
func (o *CurationInventory) GetPeersOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Peers, true
}

// SetPeers sets field value
func (o *CurationInventory) SetPeers(v int32) {
	o.Peers = v
}

// GetEntities returns the Entities field value
func (o *CurationInventory) GetEntities() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value
// and a boolean to check if the value has been set.
func (o *CurationInventory) GetEntitiesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entities, true
}

// SetEntities sets field value
func (o *CurationInventory) SetEntities(v int32) {
	o.Entities = v
}

// GetLinks returns the Links field value
func (o *CurationInventory) GetLinks() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *CurationInventory) GetLinksOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *CurationInventory) SetLinks(v int32) {
	o.Links = v
}

// GetHistoryRows returns the HistoryRows field value
func (o *CurationInventory) GetHistoryRows() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HistoryRows
}

// GetHistoryRowsOk returns a tuple with the HistoryRows field value
// and a boolean to check if the value has been set.
func (o *CurationInventory) GetHistoryRowsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HistoryRows, true
}

// SetHistoryRows sets field value
func (o *CurationInventory) SetHistoryRows(v int32) {
	o.HistoryRows = v
}

// GetSnapshotBytes returns the SnapshotBytes field value
func (o *CurationInventory) GetSnapshotBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SnapshotBytes
}

// GetSnapshotBytesOk returns a tuple with the SnapshotBytes field value
// and a boolean to check if the value has been set.
func (o *CurationInventory) GetSnapshotBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SnapshotBytes, true
}

// SetSnapshotBytes sets field value
func (o *CurationInventory) SetSnapshotBytes(v int32) {
	o.SnapshotBytes = v
}

// GetSourceBytes returns the SourceBytes field value
func (o *CurationInventory) GetSourceBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SourceBytes
}

// GetSourceBytesOk returns a tuple with the SourceBytes field value
// and a boolean to check if the value has been set.
func (o *CurationInventory) GetSourceBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceBytes, true
}

// SetSourceBytes sets field value
func (o *CurationInventory) SetSourceBytes(v int32) {
	o.SourceBytes = v
}

func (o CurationInventory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationInventory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["targets"] = o.Targets
	toSerialize["observations"] = o.Observations
	toSerialize["peers"] = o.Peers
	toSerialize["entities"] = o.Entities
	toSerialize["links"] = o.Links
	toSerialize["history_rows"] = o.HistoryRows
	toSerialize["snapshot_bytes"] = o.SnapshotBytes
	toSerialize["source_bytes"] = o.SourceBytes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CurationInventory) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"targets",
		"observations",
		"peers",
		"entities",
		"links",
		"history_rows",
		"snapshot_bytes",
		"source_bytes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationInventory := _CurationInventory{}

	err = json.Unmarshal(data, &varCurationInventory)

	if err != nil {
		return err
	}

	*o = CurationInventory(varCurationInventory)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "targets")
		delete(additionalProperties, "observations")
		delete(additionalProperties, "peers")
		delete(additionalProperties, "entities")
		delete(additionalProperties, "links")
		delete(additionalProperties, "history_rows")
		delete(additionalProperties, "snapshot_bytes")
		delete(additionalProperties, "source_bytes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurationInventory struct {
	value *CurationInventory
	isSet bool
}

func (v NullableCurationInventory) Get() *CurationInventory {
	return v.value
}

func (v *NullableCurationInventory) Set(val *CurationInventory) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationInventory) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationInventory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationInventory(val *CurationInventory) *NullableCurationInventory {
	return &NullableCurationInventory{value: val, isSet: true}
}

func (v NullableCurationInventory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationInventory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


