/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the CurationPreviewRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationPreviewRequest{}

// CurationPreviewRequest struct for CurationPreviewRequest
type CurationPreviewRequest struct {
	Protocol string `json:"protocol"`
	MemoryIds []string `json:"memory_ids"`
	AdditionalProperties map[string]interface{}
}

type _CurationPreviewRequest CurationPreviewRequest

// NewCurationPreviewRequest instantiates a new CurationPreviewRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationPreviewRequest(protocol string, memoryIds []string) *CurationPreviewRequest {
	this := CurationPreviewRequest{}
	this.Protocol = protocol
	this.MemoryIds = memoryIds
	return &this
}

// NewCurationPreviewRequestWithDefaults instantiates a new CurationPreviewRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationPreviewRequestWithDefaults() *CurationPreviewRequest {
	this := CurationPreviewRequest{}
	return &this
}

// GetProtocol returns the Protocol field value
func (o *CurationPreviewRequest) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *CurationPreviewRequest) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *CurationPreviewRequest) SetProtocol(v string) {
	o.Protocol = v
}

// GetMemoryIds returns the MemoryIds field value
func (o *CurationPreviewRequest) GetMemoryIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MemoryIds
}

// GetMemoryIdsOk returns a tuple with the MemoryIds field value
// and a boolean to check if the value has been set.
func (o *CurationPreviewRequest) GetMemoryIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MemoryIds, true
}

// SetMemoryIds sets field value
func (o *CurationPreviewRequest) SetMemoryIds(v []string) {
	o.MemoryIds = v
}

func (o CurationPreviewRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationPreviewRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["protocol"] = o.Protocol
	toSerialize["memory_ids"] = o.MemoryIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CurationPreviewRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"protocol",
		"memory_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationPreviewRequest := _CurationPreviewRequest{}

	err = json.Unmarshal(data, &varCurationPreviewRequest)

	if err != nil {
		return err
	}

	*o = CurationPreviewRequest(varCurationPreviewRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "protocol")
		delete(additionalProperties, "memory_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurationPreviewRequest struct {
	value *CurationPreviewRequest
	isSet bool
}

func (v NullableCurationPreviewRequest) Get() *CurationPreviewRequest {
	return v.value
}

func (v *NullableCurationPreviewRequest) Set(val *CurationPreviewRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationPreviewRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationPreviewRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationPreviewRequest(val *CurationPreviewRequest) *NullableCurationPreviewRequest {
	return &NullableCurationPreviewRequest{value: val, isSet: true}
}

func (v NullableCurationPreviewRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationPreviewRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


