/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the CurationGuard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationGuard{}

// CurationGuard struct for CurationGuard
type CurationGuard struct {
	Protocol string `json:"protocol"`
	// Lowercase SHA-256 hex digest.
	ExpectedMemorySha256 string `json:"expected_memory_sha256"`
	// Lowercase SHA-256 hex digest.
	ExpectedSourceSha256 string `json:"expected_source_sha256"`
	RequireNoObservations bool `json:"require_no_observations"`
	RequireQuiescentConsolidation bool `json:"require_quiescent_consolidation"`
	AdditionalProperties map[string]interface{}
}

type _CurationGuard CurationGuard

// NewCurationGuard instantiates a new CurationGuard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationGuard(protocol string, expectedMemorySha256 string, expectedSourceSha256 string, requireNoObservations bool, requireQuiescentConsolidation bool) *CurationGuard {
	this := CurationGuard{}
	this.Protocol = protocol
	this.ExpectedMemorySha256 = expectedMemorySha256
	this.ExpectedSourceSha256 = expectedSourceSha256
	this.RequireNoObservations = requireNoObservations
	this.RequireQuiescentConsolidation = requireQuiescentConsolidation
	return &this
}

// NewCurationGuardWithDefaults instantiates a new CurationGuard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationGuardWithDefaults() *CurationGuard {
	this := CurationGuard{}
	return &this
}

// GetProtocol returns the Protocol field value
func (o *CurationGuard) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *CurationGuard) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *CurationGuard) SetProtocol(v string) {
	o.Protocol = v
}

// GetExpectedMemorySha256 returns the ExpectedMemorySha256 field value
func (o *CurationGuard) GetExpectedMemorySha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedMemorySha256
}

// GetExpectedMemorySha256Ok returns a tuple with the ExpectedMemorySha256 field value
// and a boolean to check if the value has been set.
func (o *CurationGuard) GetExpectedMemorySha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedMemorySha256, true
}

// SetExpectedMemorySha256 sets field value
func (o *CurationGuard) SetExpectedMemorySha256(v string) {
	o.ExpectedMemorySha256 = v
}

// GetExpectedSourceSha256 returns the ExpectedSourceSha256 field value
func (o *CurationGuard) GetExpectedSourceSha256() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedSourceSha256
}

// GetExpectedSourceSha256Ok returns a tuple with the ExpectedSourceSha256 field value
// and a boolean to check if the value has been set.
func (o *CurationGuard) GetExpectedSourceSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedSourceSha256, true
}

// SetExpectedSourceSha256 sets field value
func (o *CurationGuard) SetExpectedSourceSha256(v string) {
	o.ExpectedSourceSha256 = v
}

// GetRequireNoObservations returns the RequireNoObservations field value
func (o *CurationGuard) GetRequireNoObservations() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequireNoObservations
}

// GetRequireNoObservationsOk returns a tuple with the RequireNoObservations field value
// and a boolean to check if the value has been set.
func (o *CurationGuard) GetRequireNoObservationsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequireNoObservations, true
}

// SetRequireNoObservations sets field value
func (o *CurationGuard) SetRequireNoObservations(v bool) {
	o.RequireNoObservations = v
}

// GetRequireQuiescentConsolidation returns the RequireQuiescentConsolidation field value
func (o *CurationGuard) GetRequireQuiescentConsolidation() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequireQuiescentConsolidation
}

// GetRequireQuiescentConsolidationOk returns a tuple with the RequireQuiescentConsolidation field value
// and a boolean to check if the value has been set.
func (o *CurationGuard) GetRequireQuiescentConsolidationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequireQuiescentConsolidation, true
}

// SetRequireQuiescentConsolidation sets field value
func (o *CurationGuard) SetRequireQuiescentConsolidation(v bool) {
	o.RequireQuiescentConsolidation = v
}

func (o CurationGuard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationGuard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["protocol"] = o.Protocol
	toSerialize["expected_memory_sha256"] = o.ExpectedMemorySha256
	toSerialize["expected_source_sha256"] = o.ExpectedSourceSha256
	toSerialize["require_no_observations"] = o.RequireNoObservations
	toSerialize["require_quiescent_consolidation"] = o.RequireQuiescentConsolidation

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CurationGuard) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"protocol",
		"expected_memory_sha256",
		"expected_source_sha256",
		"require_no_observations",
		"require_quiescent_consolidation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationGuard := _CurationGuard{}

	err = json.Unmarshal(data, &varCurationGuard)

	if err != nil {
		return err
	}

	*o = CurationGuard(varCurationGuard)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "protocol")
		delete(additionalProperties, "expected_memory_sha256")
		delete(additionalProperties, "expected_source_sha256")
		delete(additionalProperties, "require_no_observations")
		delete(additionalProperties, "require_quiescent_consolidation")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurationGuard struct {
	value *CurationGuard
	isSet bool
}

func (v NullableCurationGuard) Get() *CurationGuard {
	return v.value
}

func (v *NullableCurationGuard) Set(val *CurationGuard) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationGuard) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationGuard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationGuard(val *CurationGuard) *NullableCurationGuard {
	return &NullableCurationGuard{value: val, isSet: true}
}

func (v NullableCurationGuard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationGuard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


