/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"time"
)

// checks if the CurationFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationFields{}

// CurationFields struct for CurationFields
type CurationFields struct {
	// Nonblank replacement text, at most 100000 characters
	Text *string `json:"text,omitempty"`
	// Replacement context, at most 100000 characters, or null to clear
	Context              NullableString    `json:"context,omitempty"`
	FactType             *CurationFactType `json:"fact_type,omitempty"`
	OccurredStart        NullableTime      `json:"occurred_start,omitempty"`
	OccurredEnd          NullableTime      `json:"occurred_end,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CurationFields CurationFields

// NewCurationFields instantiates a new CurationFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationFields() *CurationFields {
	this := CurationFields{}
	return &this
}

// NewCurationFieldsWithDefaults instantiates a new CurationFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationFieldsWithDefaults() *CurationFields {
	this := CurationFields{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *CurationFields) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurationFields) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *CurationFields) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *CurationFields) SetText(v string) {
	o.Text = &v
}

// GetContext returns the Context field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurationFields) GetContext() string {
	if o == nil || IsNil(o.Context.Get()) {
		var ret string
		return ret
	}
	return *o.Context.Get()
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurationFields) GetContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Context.Get(), o.Context.IsSet()
}

// HasContext returns a boolean if a field has been set.
func (o *CurationFields) HasContext() bool {
	if o != nil && o.Context.IsSet() {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *CurationFields) SetContext(v string) {
	o.Context.Set(&v)
}

// GetFactType returns the FactType field value if set, zero value otherwise.
func (o *CurationFields) GetFactType() CurationFactType {
	if o == nil || IsNil(o.FactType) {
		var ret CurationFactType
		return ret
	}
	return *o.FactType
}

// GetFactTypeOk returns a tuple with the FactType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurationFields) GetFactTypeOk() (*CurationFactType, bool) {
	if o == nil || IsNil(o.FactType) {
		return nil, false
	}
	return o.FactType, true
}

// HasFactType returns a boolean if a field has been set.
func (o *CurationFields) HasFactType() bool {
	if o != nil && !IsNil(o.FactType) {
		return true
	}

	return false
}

// SetFactType gets a reference to the given CurationFactType and assigns it to the FactType field.
func (o *CurationFields) SetFactType(v CurationFactType) {
	o.FactType = &v
}

// GetOccurredStart returns the OccurredStart field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurationFields) GetOccurredStart() time.Time {
	if o == nil || IsNil(o.OccurredStart.Get()) {
		var ret time.Time
		return ret
	}
	return *o.OccurredStart.Get()
}

// GetOccurredStartOk returns a tuple with the OccurredStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurationFields) GetOccurredStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.OccurredStart.Get(), o.OccurredStart.IsSet()
}

// HasOccurredStart returns a boolean if a field has been set.
func (o *CurationFields) HasOccurredStart() bool {
	if o != nil && o.OccurredStart.IsSet() {
		return true
	}

	return false
}

// SetOccurredStart gets a reference to the given time.Time and assigns it to the OccurredStart field.
func (o *CurationFields) SetOccurredStart(v time.Time) {
	o.OccurredStart.Set(&v)
}

// GetOccurredEnd returns the OccurredEnd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurationFields) GetOccurredEnd() time.Time {
	if o == nil || IsNil(o.OccurredEnd.Get()) {
		var ret time.Time
		return ret
	}
	return *o.OccurredEnd.Get()
}

// GetOccurredEndOk returns a tuple with the OccurredEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurationFields) GetOccurredEndOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.OccurredEnd.Get(), o.OccurredEnd.IsSet()
}

// HasOccurredEnd returns a boolean if a field has been set.
func (o *CurationFields) HasOccurredEnd() bool {
	if o != nil && o.OccurredEnd.IsSet() {
		return true
	}

	return false
}

// SetOccurredEnd gets a reference to the given time.Time and assigns it to the OccurredEnd field.
func (o *CurationFields) SetOccurredEnd(v time.Time) {
	o.OccurredEnd.Set(&v)
}

func (o CurationFields) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if o.Context.IsSet() {
		toSerialize["context"] = o.Context.Get()
	}
	if !IsNil(o.FactType) {
		toSerialize["fact_type"] = o.FactType
	}
	if o.OccurredStart.IsSet() {
		toSerialize["occurred_start"] = o.OccurredStart.Get()
	}
	if o.OccurredEnd.IsSet() {
		toSerialize["occurred_end"] = o.OccurredEnd.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CurationFields) UnmarshalJSON(data []byte) (err error) {
	varCurationFields := _CurationFields{}

	err = json.Unmarshal(data, &varCurationFields)

	if err != nil {
		return err
	}

	*o = CurationFields(varCurationFields)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "text")
		delete(additionalProperties, "context")
		delete(additionalProperties, "fact_type")
		delete(additionalProperties, "occurred_start")
		delete(additionalProperties, "occurred_end")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurationFields struct {
	value *CurationFields
	isSet bool
}

func (v NullableCurationFields) Get() *CurationFields {
	return v.value
}

func (v *NullableCurationFields) Set(val *CurationFields) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationFields) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationFields(val *CurationFields) *NullableCurationFields {
	return &NullableCurationFields{value: val, isSet: true}
}

func (v NullableCurationFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
