/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// OcrQualityReason Stable reason codes for rejected OCR.
type OcrQualityReason string

// List of OcrQualityReason
const (
	REFUSAL_OR_NO_TEXT_RESPONSE OcrQualityReason = "refusal_or_no_text_response"
	NO_MEANINGFUL_TEXT OcrQualityReason = "no_meaningful_text"
	EXCESSIVE_UNCERTAINTY OcrQualityReason = "excessive_uncertainty"
	EXCESSIVE_REPETITION OcrQualityReason = "excessive_repetition"
	UI_CHROME_ONLY OcrQualityReason = "ui_chrome_only"
)

// All allowed values of OcrQualityReason enum
var AllowedOcrQualityReasonEnumValues = []OcrQualityReason{
	"refusal_or_no_text_response",
	"no_meaningful_text",
	"excessive_uncertainty",
	"excessive_repetition",
	"ui_chrome_only",
}

func (v *OcrQualityReason) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OcrQualityReason(value)
	for _, existing := range AllowedOcrQualityReasonEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OcrQualityReason", value)
}

// NewOcrQualityReasonFromValue returns a pointer to a valid OcrQualityReason
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOcrQualityReasonFromValue(v string) (*OcrQualityReason, error) {
	ev := OcrQualityReason(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OcrQualityReason: valid values are %v", v, AllowedOcrQualityReasonEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OcrQualityReason) IsValid() bool {
	for _, existing := range AllowedOcrQualityReasonEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OcrQualityReason value
func (v OcrQualityReason) Ptr() *OcrQualityReason {
	return &v
}

type NullableOcrQualityReason struct {
	value *OcrQualityReason
	isSet bool
}

func (v NullableOcrQualityReason) Get() *OcrQualityReason {
	return v.value
}

func (v *NullableOcrQualityReason) Set(val *OcrQualityReason) {
	v.value = val
	v.isSet = true
}

func (v NullableOcrQualityReason) IsSet() bool {
	return v.isSet
}

func (v *NullableOcrQualityReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOcrQualityReason(val *OcrQualityReason) *NullableOcrQualityReason {
	return &NullableOcrQualityReason{value: val, isSet: true}
}

func (v NullableOcrQualityReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOcrQualityReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

