/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the CurationReceipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationReceipt{}

// CurationReceipt struct for CurationReceipt
type CurationReceipt struct {
	Protocol *string `json:"protocol,omitempty"`
	BankId string `json:"bank_id"`
	BatchId string `json:"batch_id" validate:"regexp=^[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}$"`
	ManifestRevision string `json:"manifest_revision" validate:"regexp=^[0-9a-f]{64}$"`
	ReceiptRevision string `json:"receipt_revision" validate:"regexp=^[0-9a-f]{64}$"`
	Status string `json:"status"`
	Inventory CurationInventory `json:"inventory"`
	MaintenanceDebt MaintenanceDebt `json:"maintenance_debt"`
	AdditionalProperties map[string]interface{}
}

type _CurationReceipt CurationReceipt

// NewCurationReceipt instantiates a new CurationReceipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationReceipt(bankId string, batchId string, manifestRevision string, receiptRevision string, status string, inventory CurationInventory, maintenanceDebt MaintenanceDebt) *CurationReceipt {
	this := CurationReceipt{}
	var protocol string = "raw-curation-v2"
	this.Protocol = &protocol
	this.BankId = bankId
	this.BatchId = batchId
	this.ManifestRevision = manifestRevision
	this.ReceiptRevision = receiptRevision
	this.Status = status
	this.Inventory = inventory
	this.MaintenanceDebt = maintenanceDebt
	return &this
}

// NewCurationReceiptWithDefaults instantiates a new CurationReceipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationReceiptWithDefaults() *CurationReceipt {
	this := CurationReceipt{}
	var protocol string = "raw-curation-v2"
	this.Protocol = &protocol
	return &this
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *CurationReceipt) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurationReceipt) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *CurationReceipt) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *CurationReceipt) SetProtocol(v string) {
	o.Protocol = &v
}

// GetBankId returns the BankId field value
func (o *CurationReceipt) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *CurationReceipt) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *CurationReceipt) SetBankId(v string) {
	o.BankId = v
}

// GetBatchId returns the BatchId field value
func (o *CurationReceipt) GetBatchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BatchId
}

// GetBatchIdOk returns a tuple with the BatchId field value
// and a boolean to check if the value has been set.
func (o *CurationReceipt) GetBatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BatchId, true
}

// SetBatchId sets field value
func (o *CurationReceipt) SetBatchId(v string) {
	o.BatchId = v
}

// GetManifestRevision returns the ManifestRevision field value
func (o *CurationReceipt) GetManifestRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ManifestRevision
}

// GetManifestRevisionOk returns a tuple with the ManifestRevision field value
// and a boolean to check if the value has been set.
func (o *CurationReceipt) GetManifestRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManifestRevision, true
}

// SetManifestRevision sets field value
func (o *CurationReceipt) SetManifestRevision(v string) {
	o.ManifestRevision = v
}

// GetReceiptRevision returns the ReceiptRevision field value
func (o *CurationReceipt) GetReceiptRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReceiptRevision
}

// GetReceiptRevisionOk returns a tuple with the ReceiptRevision field value
// and a boolean to check if the value has been set.
func (o *CurationReceipt) GetReceiptRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceiptRevision, true
}

// SetReceiptRevision sets field value
func (o *CurationReceipt) SetReceiptRevision(v string) {
	o.ReceiptRevision = v
}

// GetStatus returns the Status field value
func (o *CurationReceipt) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CurationReceipt) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CurationReceipt) SetStatus(v string) {
	o.Status = v
}

// GetInventory returns the Inventory field value
func (o *CurationReceipt) GetInventory() CurationInventory {
	if o == nil {
		var ret CurationInventory
		return ret
	}

	return o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value
// and a boolean to check if the value has been set.
func (o *CurationReceipt) GetInventoryOk() (*CurationInventory, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Inventory, true
}

// SetInventory sets field value
func (o *CurationReceipt) SetInventory(v CurationInventory) {
	o.Inventory = v
}

// GetMaintenanceDebt returns the MaintenanceDebt field value
func (o *CurationReceipt) GetMaintenanceDebt() MaintenanceDebt {
	if o == nil {
		var ret MaintenanceDebt
		return ret
	}

	return o.MaintenanceDebt
}

// GetMaintenanceDebtOk returns a tuple with the MaintenanceDebt field value
// and a boolean to check if the value has been set.
func (o *CurationReceipt) GetMaintenanceDebtOk() (*MaintenanceDebt, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaintenanceDebt, true
}

// SetMaintenanceDebt sets field value
func (o *CurationReceipt) SetMaintenanceDebt(v MaintenanceDebt) {
	o.MaintenanceDebt = v
}

func (o CurationReceipt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationReceipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	toSerialize["bank_id"] = o.BankId
	toSerialize["batch_id"] = o.BatchId
	toSerialize["manifest_revision"] = o.ManifestRevision
	toSerialize["receipt_revision"] = o.ReceiptRevision
	toSerialize["status"] = o.Status
	toSerialize["inventory"] = o.Inventory
	toSerialize["maintenance_debt"] = o.MaintenanceDebt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CurationReceipt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bank_id",
		"batch_id",
		"manifest_revision",
		"receipt_revision",
		"status",
		"inventory",
		"maintenance_debt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationReceipt := _CurationReceipt{}

	err = json.Unmarshal(data, &varCurationReceipt)

	if err != nil {
		return err
	}

	*o = CurationReceipt(varCurationReceipt)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "protocol")
		delete(additionalProperties, "bank_id")
		delete(additionalProperties, "batch_id")
		delete(additionalProperties, "manifest_revision")
		delete(additionalProperties, "receipt_revision")
		delete(additionalProperties, "status")
		delete(additionalProperties, "inventory")
		delete(additionalProperties, "maintenance_debt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurationReceipt struct {
	value *CurationReceipt
	isSet bool
}

func (v NullableCurationReceipt) Get() *CurationReceipt {
	return v.value
}

func (v *NullableCurationReceipt) Set(val *CurationReceipt) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationReceipt(val *CurationReceipt) *NullableCurationReceipt {
	return &NullableCurationReceipt{value: val, isSet: true}
}

func (v NullableCurationReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


