/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the CurationApplyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationApplyRequest{}

// CurationApplyRequest struct for CurationApplyRequest
type CurationApplyRequest struct {
	Protocol string `json:"protocol"`
	ExpectedClosureRevision string `json:"expected_closure_revision" validate:"regexp=^[0-9a-f]{64}$"`
	Changes []CurationChange `json:"changes"`
	AdditionalProperties map[string]interface{}
}

type _CurationApplyRequest CurationApplyRequest

// NewCurationApplyRequest instantiates a new CurationApplyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationApplyRequest(protocol string, expectedClosureRevision string, changes []CurationChange) *CurationApplyRequest {
	this := CurationApplyRequest{}
	this.Protocol = protocol
	this.ExpectedClosureRevision = expectedClosureRevision
	this.Changes = changes
	return &this
}

// NewCurationApplyRequestWithDefaults instantiates a new CurationApplyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationApplyRequestWithDefaults() *CurationApplyRequest {
	this := CurationApplyRequest{}
	return &this
}

// GetProtocol returns the Protocol field value
func (o *CurationApplyRequest) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *CurationApplyRequest) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *CurationApplyRequest) SetProtocol(v string) {
	o.Protocol = v
}

// GetExpectedClosureRevision returns the ExpectedClosureRevision field value
func (o *CurationApplyRequest) GetExpectedClosureRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedClosureRevision
}

// GetExpectedClosureRevisionOk returns a tuple with the ExpectedClosureRevision field value
// and a boolean to check if the value has been set.
func (o *CurationApplyRequest) GetExpectedClosureRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedClosureRevision, true
}

// SetExpectedClosureRevision sets field value
func (o *CurationApplyRequest) SetExpectedClosureRevision(v string) {
	o.ExpectedClosureRevision = v
}

// GetChanges returns the Changes field value
func (o *CurationApplyRequest) GetChanges() []CurationChange {
	if o == nil {
		var ret []CurationChange
		return ret
	}

	return o.Changes
}

// GetChangesOk returns a tuple with the Changes field value
// and a boolean to check if the value has been set.
func (o *CurationApplyRequest) GetChangesOk() ([]CurationChange, bool) {
	if o == nil {
		return nil, false
	}
	return o.Changes, true
}

// SetChanges sets field value
func (o *CurationApplyRequest) SetChanges(v []CurationChange) {
	o.Changes = v
}

func (o CurationApplyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationApplyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["protocol"] = o.Protocol
	toSerialize["expected_closure_revision"] = o.ExpectedClosureRevision
	toSerialize["changes"] = o.Changes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CurationApplyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"protocol",
		"expected_closure_revision",
		"changes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationApplyRequest := _CurationApplyRequest{}

	err = json.Unmarshal(data, &varCurationApplyRequest)

	if err != nil {
		return err
	}

	*o = CurationApplyRequest(varCurationApplyRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "protocol")
		delete(additionalProperties, "expected_closure_revision")
		delete(additionalProperties, "changes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurationApplyRequest struct {
	value *CurationApplyRequest
	isSet bool
}

func (v NullableCurationApplyRequest) Get() *CurationApplyRequest {
	return v.value
}

func (v *NullableCurationApplyRequest) Set(val *CurationApplyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationApplyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationApplyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationApplyRequest(val *CurationApplyRequest) *NullableCurationApplyRequest {
	return &NullableCurationApplyRequest{value: val, isSet: true}
}

func (v NullableCurationApplyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationApplyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


