/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FileConvertRetainOperationDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileConvertRetainOperationDetails{}

// FileConvertRetainOperationDetails A deterministic terminal outcome from a file conversion operation.
type FileConvertRetainOperationDetails struct {
	// Discriminator: which operation type this detail describes.
	OperationType *string `json:"operation_type,omitempty"`
	// Stable failure class callers may use to decide whether the source artifact is retryable.
	FailureClass string `json:"failure_class"`
	// The OCR rejection reason, or empty_content when every parser extracted no text.
	FailureReason string `json:"failure_reason"`
	Parsers []string `json:"parsers,omitempty"`
}

type _FileConvertRetainOperationDetails FileConvertRetainOperationDetails

// NewFileConvertRetainOperationDetails instantiates a new FileConvertRetainOperationDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileConvertRetainOperationDetails(failureClass string, failureReason string) *FileConvertRetainOperationDetails {
	this := FileConvertRetainOperationDetails{}
	var operationType string = "file_convert_retain"
	this.OperationType = &operationType
	this.FailureClass = failureClass
	this.FailureReason = failureReason
	return &this
}

// NewFileConvertRetainOperationDetailsWithDefaults instantiates a new FileConvertRetainOperationDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileConvertRetainOperationDetailsWithDefaults() *FileConvertRetainOperationDetails {
	this := FileConvertRetainOperationDetails{}
	var operationType string = "file_convert_retain"
	this.OperationType = &operationType
	return &this
}

// GetOperationType returns the OperationType field value if set, zero value otherwise.
func (o *FileConvertRetainOperationDetails) GetOperationType() string {
	if o == nil || IsNil(o.OperationType) {
		var ret string
		return ret
	}
	return *o.OperationType
}

// GetOperationTypeOk returns a tuple with the OperationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileConvertRetainOperationDetails) GetOperationTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OperationType) {
		return nil, false
	}
	return o.OperationType, true
}

// HasOperationType returns a boolean if a field has been set.
func (o *FileConvertRetainOperationDetails) HasOperationType() bool {
	if o != nil && !IsNil(o.OperationType) {
		return true
	}

	return false
}

// SetOperationType gets a reference to the given string and assigns it to the OperationType field.
func (o *FileConvertRetainOperationDetails) SetOperationType(v string) {
	o.OperationType = &v
}

// GetFailureClass returns the FailureClass field value
func (o *FileConvertRetainOperationDetails) GetFailureClass() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FailureClass
}

// GetFailureClassOk returns a tuple with the FailureClass field value
// and a boolean to check if the value has been set.
func (o *FileConvertRetainOperationDetails) GetFailureClassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailureClass, true
}

// SetFailureClass sets field value
func (o *FileConvertRetainOperationDetails) SetFailureClass(v string) {
	o.FailureClass = v
}

// GetFailureReason returns the FailureReason field value
func (o *FileConvertRetainOperationDetails) GetFailureReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FailureReason
}

// GetFailureReasonOk returns a tuple with the FailureReason field value
// and a boolean to check if the value has been set.
func (o *FileConvertRetainOperationDetails) GetFailureReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailureReason, true
}

// SetFailureReason sets field value
func (o *FileConvertRetainOperationDetails) SetFailureReason(v string) {
	o.FailureReason = v
}

// GetParsers returns the Parsers field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileConvertRetainOperationDetails) GetParsers() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Parsers
}

// GetParsersOk returns a tuple with the Parsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileConvertRetainOperationDetails) GetParsersOk() ([]string, bool) {
	if o == nil || IsNil(o.Parsers) {
		return nil, false
	}
	return o.Parsers, true
}

// HasParsers returns a boolean if a field has been set.
func (o *FileConvertRetainOperationDetails) HasParsers() bool {
	if o != nil && !IsNil(o.Parsers) {
		return true
	}

	return false
}

// SetParsers gets a reference to the given []string and assigns it to the Parsers field.
func (o *FileConvertRetainOperationDetails) SetParsers(v []string) {
	o.Parsers = v
}

func (o FileConvertRetainOperationDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileConvertRetainOperationDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OperationType) {
		toSerialize["operation_type"] = o.OperationType
	}
	toSerialize["failure_class"] = o.FailureClass
	toSerialize["failure_reason"] = o.FailureReason
	if o.Parsers != nil {
		toSerialize["parsers"] = o.Parsers
	}
	return toSerialize, nil
}

func (o *FileConvertRetainOperationDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"failure_class",
		"failure_reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFileConvertRetainOperationDetails := _FileConvertRetainOperationDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFileConvertRetainOperationDetails)

	if err != nil {
		return err
	}

	*o = FileConvertRetainOperationDetails(varFileConvertRetainOperationDetails)

	return err
}

type NullableFileConvertRetainOperationDetails struct {
	value *FileConvertRetainOperationDetails
	isSet bool
}

func (v NullableFileConvertRetainOperationDetails) Get() *FileConvertRetainOperationDetails {
	return v.value
}

func (v *NullableFileConvertRetainOperationDetails) Set(val *FileConvertRetainOperationDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableFileConvertRetainOperationDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableFileConvertRetainOperationDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileConvertRetainOperationDetails(val *FileConvertRetainOperationDetails) *NullableFileConvertRetainOperationDetails {
	return &NullableFileConvertRetainOperationDetails{value: val, isSet: true}
}

func (v NullableFileConvertRetainOperationDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileConvertRetainOperationDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


