/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the CurationChange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationChange{}

// CurationChange struct for CurationChange
type CurationChange struct {
	MemoryId string `json:"memory_id"`
	MemoryRevision string `json:"memory_revision" validate:"regexp=^[0-9a-f]{64}$"`
	SourceRevision string `json:"source_revision" validate:"regexp=^[0-9a-f]{64}$"`
	Action string `json:"action"`
	Reason string `json:"reason"`
	Fields *CurationFields `json:"fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CurationChange CurationChange

// NewCurationChange instantiates a new CurationChange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationChange(memoryId string, memoryRevision string, sourceRevision string, action string, reason string) *CurationChange {
	this := CurationChange{}
	this.MemoryId = memoryId
	this.MemoryRevision = memoryRevision
	this.SourceRevision = sourceRevision
	this.Action = action
	this.Reason = reason
	return &this
}

// NewCurationChangeWithDefaults instantiates a new CurationChange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationChangeWithDefaults() *CurationChange {
	this := CurationChange{}
	return &this
}

// GetMemoryId returns the MemoryId field value
func (o *CurationChange) GetMemoryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemoryId
}

// GetMemoryIdOk returns a tuple with the MemoryId field value
// and a boolean to check if the value has been set.
func (o *CurationChange) GetMemoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryId, true
}

// SetMemoryId sets field value
func (o *CurationChange) SetMemoryId(v string) {
	o.MemoryId = v
}

// GetMemoryRevision returns the MemoryRevision field value
func (o *CurationChange) GetMemoryRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemoryRevision
}

// GetMemoryRevisionOk returns a tuple with the MemoryRevision field value
// and a boolean to check if the value has been set.
func (o *CurationChange) GetMemoryRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryRevision, true
}

// SetMemoryRevision sets field value
func (o *CurationChange) SetMemoryRevision(v string) {
	o.MemoryRevision = v
}

// GetSourceRevision returns the SourceRevision field value
func (o *CurationChange) GetSourceRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceRevision
}

// GetSourceRevisionOk returns a tuple with the SourceRevision field value
// and a boolean to check if the value has been set.
func (o *CurationChange) GetSourceRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceRevision, true
}

// SetSourceRevision sets field value
func (o *CurationChange) SetSourceRevision(v string) {
	o.SourceRevision = v
}

// GetAction returns the Action field value
func (o *CurationChange) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *CurationChange) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *CurationChange) SetAction(v string) {
	o.Action = v
}

// GetReason returns the Reason field value
func (o *CurationChange) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *CurationChange) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *CurationChange) SetReason(v string) {
	o.Reason = v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *CurationChange) GetFields() CurationFields {
	if o == nil || IsNil(o.Fields) {
		var ret CurationFields
		return ret
	}
	return *o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurationChange) GetFieldsOk() (*CurationFields, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *CurationChange) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given CurationFields and assigns it to the Fields field.
func (o *CurationChange) SetFields(v CurationFields) {
	o.Fields = &v
}

func (o CurationChange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationChange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["memory_id"] = o.MemoryId
	toSerialize["memory_revision"] = o.MemoryRevision
	toSerialize["source_revision"] = o.SourceRevision
	toSerialize["action"] = o.Action
	toSerialize["reason"] = o.Reason
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CurationChange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"memory_id",
		"memory_revision",
		"source_revision",
		"action",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationChange := _CurationChange{}

	err = json.Unmarshal(data, &varCurationChange)

	if err != nil {
		return err
	}

	*o = CurationChange(varCurationChange)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "memory_id")
		delete(additionalProperties, "memory_revision")
		delete(additionalProperties, "source_revision")
		delete(additionalProperties, "action")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurationChange struct {
	value *CurationChange
	isSet bool
}

func (v NullableCurationChange) Get() *CurationChange {
	return v.value
}

func (v *NullableCurationChange) Set(val *CurationChange) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationChange) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationChange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationChange(val *CurationChange) *NullableCurationChange {
	return &NullableCurationChange{value: val, isSet: true}
}

func (v NullableCurationChange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationChange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


