/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// CurationFactType the model 'CurationFactType'
type CurationFactType string

// List of CurationFactType
const (
	WORLD CurationFactType = "world"
	EXPERIENCE CurationFactType = "experience"
)

// All allowed values of CurationFactType enum
var AllowedCurationFactTypeEnumValues = []CurationFactType{
	"world",
	"experience",
}

func (v *CurationFactType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CurationFactType(value)
	for _, existing := range AllowedCurationFactTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CurationFactType", value)
}

// NewCurationFactTypeFromValue returns a pointer to a valid CurationFactType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCurationFactTypeFromValue(v string) (*CurationFactType, error) {
	ev := CurationFactType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CurationFactType: valid values are %v", v, AllowedCurationFactTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CurationFactType) IsValid() bool {
	for _, existing := range AllowedCurationFactTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CurationFactType value
func (v CurationFactType) Ptr() *CurationFactType {
	return &v
}

type NullableCurationFactType struct {
	value *CurationFactType
	isSet bool
}

func (v NullableCurationFactType) Get() *CurationFactType {
	return v.value
}

func (v *NullableCurationFactType) Set(val *CurationFactType) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationFactType) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationFactType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationFactType(val *CurationFactType) *NullableCurationFactType {
	return &NullableCurationFactType{value: val, isSet: true}
}

func (v NullableCurationFactType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationFactType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

