/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the CurationTargetRevision type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationTargetRevision{}

// CurationTargetRevision struct for CurationTargetRevision
type CurationTargetRevision struct {
	MemoryId string `json:"memory_id"`
	MemoryRevision string `json:"memory_revision" validate:"regexp=^[0-9a-f]{64}$"`
	SourceRevision string `json:"source_revision" validate:"regexp=^[0-9a-f]{64}$"`
	AdditionalProperties map[string]interface{}
}

type _CurationTargetRevision CurationTargetRevision

// NewCurationTargetRevision instantiates a new CurationTargetRevision object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationTargetRevision(memoryId string, memoryRevision string, sourceRevision string) *CurationTargetRevision {
	this := CurationTargetRevision{}
	this.MemoryId = memoryId
	this.MemoryRevision = memoryRevision
	this.SourceRevision = sourceRevision
	return &this
}

// NewCurationTargetRevisionWithDefaults instantiates a new CurationTargetRevision object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationTargetRevisionWithDefaults() *CurationTargetRevision {
	this := CurationTargetRevision{}
	return &this
}

// GetMemoryId returns the MemoryId field value
func (o *CurationTargetRevision) GetMemoryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemoryId
}

// GetMemoryIdOk returns a tuple with the MemoryId field value
// and a boolean to check if the value has been set.
func (o *CurationTargetRevision) GetMemoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryId, true
}

// SetMemoryId sets field value
func (o *CurationTargetRevision) SetMemoryId(v string) {
	o.MemoryId = v
}

// GetMemoryRevision returns the MemoryRevision field value
func (o *CurationTargetRevision) GetMemoryRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemoryRevision
}

// GetMemoryRevisionOk returns a tuple with the MemoryRevision field value
// and a boolean to check if the value has been set.
func (o *CurationTargetRevision) GetMemoryRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryRevision, true
}

// SetMemoryRevision sets field value
func (o *CurationTargetRevision) SetMemoryRevision(v string) {
	o.MemoryRevision = v
}

// GetSourceRevision returns the SourceRevision field value
func (o *CurationTargetRevision) GetSourceRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceRevision
}

// GetSourceRevisionOk returns a tuple with the SourceRevision field value
// and a boolean to check if the value has been set.
func (o *CurationTargetRevision) GetSourceRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceRevision, true
}

// SetSourceRevision sets field value
func (o *CurationTargetRevision) SetSourceRevision(v string) {
	o.SourceRevision = v
}

func (o CurationTargetRevision) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationTargetRevision) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["memory_id"] = o.MemoryId
	toSerialize["memory_revision"] = o.MemoryRevision
	toSerialize["source_revision"] = o.SourceRevision

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CurationTargetRevision) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"memory_id",
		"memory_revision",
		"source_revision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationTargetRevision := _CurationTargetRevision{}

	err = json.Unmarshal(data, &varCurationTargetRevision)

	if err != nil {
		return err
	}

	*o = CurationTargetRevision(varCurationTargetRevision)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "memory_id")
		delete(additionalProperties, "memory_revision")
		delete(additionalProperties, "source_revision")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurationTargetRevision struct {
	value *CurationTargetRevision
	isSet bool
}

func (v NullableCurationTargetRevision) Get() *CurationTargetRevision {
	return v.value
}

func (v *NullableCurationTargetRevision) Set(val *CurationTargetRevision) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationTargetRevision) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationTargetRevision) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationTargetRevision(val *CurationTargetRevision) *NullableCurationTargetRevision {
	return &NullableCurationTargetRevision{value: val, isSet: true}
}

func (v NullableCurationTargetRevision) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationTargetRevision) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


