/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the MaintenanceDebt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MaintenanceDebt{}

// MaintenanceDebt struct for MaintenanceDebt
type MaintenanceDebt struct {
	Consolidation *bool `json:"consolidation,omitempty"`
	Graph *bool `json:"graph,omitempty"`
	ModelRefresh *bool `json:"model_refresh,omitempty"`
	MemoryIds []string `json:"memory_ids"`
	AdditionalProperties map[string]interface{}
}

type _MaintenanceDebt MaintenanceDebt

// NewMaintenanceDebt instantiates a new MaintenanceDebt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMaintenanceDebt(memoryIds []string) *MaintenanceDebt {
	this := MaintenanceDebt{}
	var consolidation bool = true
	this.Consolidation = &consolidation
	var graph bool = true
	this.Graph = &graph
	var modelRefresh bool = true
	this.ModelRefresh = &modelRefresh
	this.MemoryIds = memoryIds
	return &this
}

// NewMaintenanceDebtWithDefaults instantiates a new MaintenanceDebt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMaintenanceDebtWithDefaults() *MaintenanceDebt {
	this := MaintenanceDebt{}
	var consolidation bool = true
	this.Consolidation = &consolidation
	var graph bool = true
	this.Graph = &graph
	var modelRefresh bool = true
	this.ModelRefresh = &modelRefresh
	return &this
}

// GetConsolidation returns the Consolidation field value if set, zero value otherwise.
func (o *MaintenanceDebt) GetConsolidation() bool {
	if o == nil || IsNil(o.Consolidation) {
		var ret bool
		return ret
	}
	return *o.Consolidation
}

// GetConsolidationOk returns a tuple with the Consolidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceDebt) GetConsolidationOk() (*bool, bool) {
	if o == nil || IsNil(o.Consolidation) {
		return nil, false
	}
	return o.Consolidation, true
}

// HasConsolidation returns a boolean if a field has been set.
func (o *MaintenanceDebt) HasConsolidation() bool {
	if o != nil && !IsNil(o.Consolidation) {
		return true
	}

	return false
}

// SetConsolidation gets a reference to the given bool and assigns it to the Consolidation field.
func (o *MaintenanceDebt) SetConsolidation(v bool) {
	o.Consolidation = &v
}

// GetGraph returns the Graph field value if set, zero value otherwise.
func (o *MaintenanceDebt) GetGraph() bool {
	if o == nil || IsNil(o.Graph) {
		var ret bool
		return ret
	}
	return *o.Graph
}

// GetGraphOk returns a tuple with the Graph field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceDebt) GetGraphOk() (*bool, bool) {
	if o == nil || IsNil(o.Graph) {
		return nil, false
	}
	return o.Graph, true
}

// HasGraph returns a boolean if a field has been set.
func (o *MaintenanceDebt) HasGraph() bool {
	if o != nil && !IsNil(o.Graph) {
		return true
	}

	return false
}

// SetGraph gets a reference to the given bool and assigns it to the Graph field.
func (o *MaintenanceDebt) SetGraph(v bool) {
	o.Graph = &v
}

// GetModelRefresh returns the ModelRefresh field value if set, zero value otherwise.
func (o *MaintenanceDebt) GetModelRefresh() bool {
	if o == nil || IsNil(o.ModelRefresh) {
		var ret bool
		return ret
	}
	return *o.ModelRefresh
}

// GetModelRefreshOk returns a tuple with the ModelRefresh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MaintenanceDebt) GetModelRefreshOk() (*bool, bool) {
	if o == nil || IsNil(o.ModelRefresh) {
		return nil, false
	}
	return o.ModelRefresh, true
}

// HasModelRefresh returns a boolean if a field has been set.
func (o *MaintenanceDebt) HasModelRefresh() bool {
	if o != nil && !IsNil(o.ModelRefresh) {
		return true
	}

	return false
}

// SetModelRefresh gets a reference to the given bool and assigns it to the ModelRefresh field.
func (o *MaintenanceDebt) SetModelRefresh(v bool) {
	o.ModelRefresh = &v
}

// GetMemoryIds returns the MemoryIds field value
func (o *MaintenanceDebt) GetMemoryIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MemoryIds
}

// GetMemoryIdsOk returns a tuple with the MemoryIds field value
// and a boolean to check if the value has been set.
func (o *MaintenanceDebt) GetMemoryIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MemoryIds, true
}

// SetMemoryIds sets field value
func (o *MaintenanceDebt) SetMemoryIds(v []string) {
	o.MemoryIds = v
}

func (o MaintenanceDebt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MaintenanceDebt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Consolidation) {
		toSerialize["consolidation"] = o.Consolidation
	}
	if !IsNil(o.Graph) {
		toSerialize["graph"] = o.Graph
	}
	if !IsNil(o.ModelRefresh) {
		toSerialize["model_refresh"] = o.ModelRefresh
	}
	toSerialize["memory_ids"] = o.MemoryIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MaintenanceDebt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"memory_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMaintenanceDebt := _MaintenanceDebt{}

	err = json.Unmarshal(data, &varMaintenanceDebt)

	if err != nil {
		return err
	}

	*o = MaintenanceDebt(varMaintenanceDebt)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "consolidation")
		delete(additionalProperties, "graph")
		delete(additionalProperties, "model_refresh")
		delete(additionalProperties, "memory_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMaintenanceDebt struct {
	value *MaintenanceDebt
	isSet bool
}

func (v NullableMaintenanceDebt) Get() *MaintenanceDebt {
	return v.value
}

func (v *NullableMaintenanceDebt) Set(val *MaintenanceDebt) {
	v.value = val
	v.isSet = true
}

func (v NullableMaintenanceDebt) IsSet() bool {
	return v.isSet
}

func (v *NullableMaintenanceDebt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMaintenanceDebt(val *MaintenanceDebt) *NullableMaintenanceDebt {
	return &NullableMaintenanceDebt{value: val, isSet: true}
}

func (v NullableMaintenanceDebt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMaintenanceDebt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


