/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CurationConflictResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationConflictResponse{}

// CurationConflictResponse String-detail conflict payload returned by raw-curation-v2 routes.
type CurationConflictResponse struct {
	Detail string `json:"detail"`
}

type _CurationConflictResponse CurationConflictResponse

// NewCurationConflictResponse instantiates a new CurationConflictResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationConflictResponse(detail string) *CurationConflictResponse {
	this := CurationConflictResponse{}
	this.Detail = detail
	return &this
}

// NewCurationConflictResponseWithDefaults instantiates a new CurationConflictResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationConflictResponseWithDefaults() *CurationConflictResponse {
	this := CurationConflictResponse{}
	return &this
}

// GetDetail returns the Detail field value
func (o *CurationConflictResponse) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *CurationConflictResponse) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *CurationConflictResponse) SetDetail(v string) {
	o.Detail = v
}

func (o CurationConflictResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationConflictResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["detail"] = o.Detail
	return toSerialize, nil
}

func (o *CurationConflictResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"detail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationConflictResponse := _CurationConflictResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCurationConflictResponse)

	if err != nil {
		return err
	}

	*o = CurationConflictResponse(varCurationConflictResponse)

	return err
}

type NullableCurationConflictResponse struct {
	value *CurationConflictResponse
	isSet bool
}

func (v NullableCurationConflictResponse) Get() *CurationConflictResponse {
	return v.value
}

func (v *NullableCurationConflictResponse) Set(val *CurationConflictResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationConflictResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationConflictResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationConflictResponse(val *CurationConflictResponse) *NullableCurationConflictResponse {
	return &NullableCurationConflictResponse{value: val, isSet: true}
}

func (v NullableCurationConflictResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationConflictResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


