/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// OperationResponseDetails - struct for OperationResponseDetails
type OperationResponseDetails struct {
	FileConvertRetainOperationDetails  *FileConvertRetainOperationDetails
	RefreshMentalModelOperationDetails *RefreshMentalModelOperationDetails
}

// FileConvertRetainOperationDetailsAsOperationResponseDetails is a convenience function that returns FileConvertRetainOperationDetails wrapped in OperationResponseDetails
func FileConvertRetainOperationDetailsAsOperationResponseDetails(v *FileConvertRetainOperationDetails) OperationResponseDetails {
	return OperationResponseDetails{
		FileConvertRetainOperationDetails: v,
	}
}

// RefreshMentalModelOperationDetailsAsOperationResponseDetails is a convenience function that returns RefreshMentalModelOperationDetails wrapped in OperationResponseDetails
func RefreshMentalModelOperationDetailsAsOperationResponseDetails(v *RefreshMentalModelOperationDetails) OperationResponseDetails {
	return OperationResponseDetails{
		RefreshMentalModelOperationDetails: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *OperationResponseDetails) UnmarshalJSON(data []byte) error {
	// Trial-decoding by shape accepts mismatched operation_type values and
	// treats null as matching both schemas. Null is an empty union; all other
	// payloads must select exactly the variant named on the wire.
	*dst = OperationResponseDetails{}
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		return nil
	}
	var tag struct {
		OperationType string `json:"operation_type"`
	}
	if err := json.Unmarshal(data, &tag); err != nil {
		return err
	}
	switch tag.OperationType {
	case "file_convert_retain":
		var detail FileConvertRetainOperationDetails
		if err := json.Unmarshal(data, &detail); err != nil {
			return err
		}
		dst.FileConvertRetainOperationDetails = &detail
	case "refresh_mental_model":
		var detail RefreshMentalModelOperationDetails
		if err := json.Unmarshal(data, &detail); err != nil {
			return err
		}
		dst.RefreshMentalModelOperationDetails = &detail
	default:
		return fmt.Errorf("unknown operation details type: %q", tag.OperationType)
	}
	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OperationResponseDetails) MarshalJSON() ([]byte, error) {
	if src.FileConvertRetainOperationDetails != nil {
		return json.Marshal(&src.FileConvertRetainOperationDetails)
	}

	if src.RefreshMentalModelOperationDetails != nil {
		return json.Marshal(&src.RefreshMentalModelOperationDetails)
	}

	return []byte("null"), nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OperationResponseDetails) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FileConvertRetainOperationDetails != nil {
		return obj.FileConvertRetainOperationDetails
	}

	if obj.RefreshMentalModelOperationDetails != nil {
		return obj.RefreshMentalModelOperationDetails
	}

	// all schemas are nil
	return nil
}

type NullableOperationResponseDetails struct {
	value *OperationResponseDetails
	isSet bool
}

func (v NullableOperationResponseDetails) Get() *OperationResponseDetails {
	return v.value
}

func (v *NullableOperationResponseDetails) Set(val *OperationResponseDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationResponseDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationResponseDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationResponseDetails(val *OperationResponseDetails) *NullableOperationResponseDetails {
	return &NullableOperationResponseDetails{value: val, isSet: true}
}

func (v NullableOperationResponseDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationResponseDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
