/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the CurationRevertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationRevertRequest{}

// CurationRevertRequest struct for CurationRevertRequest
type CurationRevertRequest struct {
	Protocol string `json:"protocol"`
	ExpectedReceiptRevision string `json:"expected_receipt_revision" validate:"regexp=^[0-9a-f]{64}$"`
	AdditionalProperties map[string]interface{}
}

type _CurationRevertRequest CurationRevertRequest

// NewCurationRevertRequest instantiates a new CurationRevertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationRevertRequest(protocol string, expectedReceiptRevision string) *CurationRevertRequest {
	this := CurationRevertRequest{}
	this.Protocol = protocol
	this.ExpectedReceiptRevision = expectedReceiptRevision
	return &this
}

// NewCurationRevertRequestWithDefaults instantiates a new CurationRevertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationRevertRequestWithDefaults() *CurationRevertRequest {
	this := CurationRevertRequest{}
	return &this
}

// GetProtocol returns the Protocol field value
func (o *CurationRevertRequest) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *CurationRevertRequest) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *CurationRevertRequest) SetProtocol(v string) {
	o.Protocol = v
}

// GetExpectedReceiptRevision returns the ExpectedReceiptRevision field value
func (o *CurationRevertRequest) GetExpectedReceiptRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpectedReceiptRevision
}

// GetExpectedReceiptRevisionOk returns a tuple with the ExpectedReceiptRevision field value
// and a boolean to check if the value has been set.
func (o *CurationRevertRequest) GetExpectedReceiptRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpectedReceiptRevision, true
}

// SetExpectedReceiptRevision sets field value
func (o *CurationRevertRequest) SetExpectedReceiptRevision(v string) {
	o.ExpectedReceiptRevision = v
}

func (o CurationRevertRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationRevertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["protocol"] = o.Protocol
	toSerialize["expected_receipt_revision"] = o.ExpectedReceiptRevision

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CurationRevertRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"protocol",
		"expected_receipt_revision",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationRevertRequest := _CurationRevertRequest{}

	err = json.Unmarshal(data, &varCurationRevertRequest)

	if err != nil {
		return err
	}

	*o = CurationRevertRequest(varCurationRevertRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "protocol")
		delete(additionalProperties, "expected_receipt_revision")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurationRevertRequest struct {
	value *CurationRevertRequest
	isSet bool
}

func (v NullableCurationRevertRequest) Get() *CurationRevertRequest {
	return v.value
}

func (v *NullableCurationRevertRequest) Set(val *CurationRevertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationRevertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationRevertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationRevertRequest(val *CurationRevertRequest) *NullableCurationRevertRequest {
	return &NullableCurationRevertRequest{value: val, isSet: true}
}

func (v NullableCurationRevertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationRevertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


