/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"fmt"
)

// checks if the CurationPreview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurationPreview{}

// CurationPreview struct for CurationPreview
type CurationPreview struct {
	Protocol *string `json:"protocol,omitempty"`
	ClosureRevision string `json:"closure_revision" validate:"regexp=^[0-9a-f]{64}$"`
	Targets []CurationTargetRevision `json:"targets"`
	Inventory CurationInventory `json:"inventory"`
	AdditionalProperties map[string]interface{}
}

type _CurationPreview CurationPreview

// NewCurationPreview instantiates a new CurationPreview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurationPreview(closureRevision string, targets []CurationTargetRevision, inventory CurationInventory) *CurationPreview {
	this := CurationPreview{}
	var protocol string = "raw-curation-v2"
	this.Protocol = &protocol
	this.ClosureRevision = closureRevision
	this.Targets = targets
	this.Inventory = inventory
	return &this
}

// NewCurationPreviewWithDefaults instantiates a new CurationPreview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurationPreviewWithDefaults() *CurationPreview {
	this := CurationPreview{}
	var protocol string = "raw-curation-v2"
	this.Protocol = &protocol
	return &this
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *CurationPreview) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurationPreview) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *CurationPreview) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *CurationPreview) SetProtocol(v string) {
	o.Protocol = &v
}

// GetClosureRevision returns the ClosureRevision field value
func (o *CurationPreview) GetClosureRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClosureRevision
}

// GetClosureRevisionOk returns a tuple with the ClosureRevision field value
// and a boolean to check if the value has been set.
func (o *CurationPreview) GetClosureRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClosureRevision, true
}

// SetClosureRevision sets field value
func (o *CurationPreview) SetClosureRevision(v string) {
	o.ClosureRevision = v
}

// GetTargets returns the Targets field value
func (o *CurationPreview) GetTargets() []CurationTargetRevision {
	if o == nil {
		var ret []CurationTargetRevision
		return ret
	}

	return o.Targets
}

// GetTargetsOk returns a tuple with the Targets field value
// and a boolean to check if the value has been set.
func (o *CurationPreview) GetTargetsOk() ([]CurationTargetRevision, bool) {
	if o == nil {
		return nil, false
	}
	return o.Targets, true
}

// SetTargets sets field value
func (o *CurationPreview) SetTargets(v []CurationTargetRevision) {
	o.Targets = v
}

// GetInventory returns the Inventory field value
func (o *CurationPreview) GetInventory() CurationInventory {
	if o == nil {
		var ret CurationInventory
		return ret
	}

	return o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value
// and a boolean to check if the value has been set.
func (o *CurationPreview) GetInventoryOk() (*CurationInventory, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Inventory, true
}

// SetInventory sets field value
func (o *CurationPreview) SetInventory(v CurationInventory) {
	o.Inventory = v
}

func (o CurationPreview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurationPreview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	toSerialize["closure_revision"] = o.ClosureRevision
	toSerialize["targets"] = o.Targets
	toSerialize["inventory"] = o.Inventory

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CurationPreview) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"closure_revision",
		"targets",
		"inventory",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCurationPreview := _CurationPreview{}

	err = json.Unmarshal(data, &varCurationPreview)

	if err != nil {
		return err
	}

	*o = CurationPreview(varCurationPreview)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "protocol")
		delete(additionalProperties, "closure_revision")
		delete(additionalProperties, "targets")
		delete(additionalProperties, "inventory")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCurationPreview struct {
	value *CurationPreview
	isSet bool
}

func (v NullableCurationPreview) Get() *CurationPreview {
	return v.value
}

func (v *NullableCurationPreview) Set(val *CurationPreview) {
	v.value = val
	v.isSet = true
}

func (v NullableCurationPreview) IsSet() bool {
	return v.isSet
}

func (v *NullableCurationPreview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurationPreview(val *CurationPreview) *NullableCurationPreview {
	return &NullableCurationPreview{value: val, isSet: true}
}

func (v NullableCurationPreview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurationPreview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


