/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// OperationResponseDetails - struct for OperationResponseDetails
type OperationResponseDetails struct {
	FileConvertRetainOperationDetails *FileConvertRetainOperationDetails
	RefreshMentalModelOperationDetails *RefreshMentalModelOperationDetails
}

// FileConvertRetainOperationDetailsAsOperationResponseDetails is a convenience function that returns FileConvertRetainOperationDetails wrapped in OperationResponseDetails
func FileConvertRetainOperationDetailsAsOperationResponseDetails(v *FileConvertRetainOperationDetails) OperationResponseDetails {
	return OperationResponseDetails{
		FileConvertRetainOperationDetails: v,
	}
}

// RefreshMentalModelOperationDetailsAsOperationResponseDetails is a convenience function that returns RefreshMentalModelOperationDetails wrapped in OperationResponseDetails
func RefreshMentalModelOperationDetailsAsOperationResponseDetails(v *RefreshMentalModelOperationDetails) OperationResponseDetails {
	return OperationResponseDetails{
		RefreshMentalModelOperationDetails: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *OperationResponseDetails) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into FileConvertRetainOperationDetails
	err = newStrictDecoder(data).Decode(&dst.FileConvertRetainOperationDetails)
	if err == nil {
		jsonFileConvertRetainOperationDetails, _ := json.Marshal(dst.FileConvertRetainOperationDetails)
		if string(jsonFileConvertRetainOperationDetails) == "{}" { // empty struct
			dst.FileConvertRetainOperationDetails = nil
		} else {
			if err = validator.Validate(dst.FileConvertRetainOperationDetails); err != nil {
				dst.FileConvertRetainOperationDetails = nil
			} else {
				match++
			}
		}
	} else {
		dst.FileConvertRetainOperationDetails = nil
	}

	// try to unmarshal data into RefreshMentalModelOperationDetails
	err = newStrictDecoder(data).Decode(&dst.RefreshMentalModelOperationDetails)
	if err == nil {
		jsonRefreshMentalModelOperationDetails, _ := json.Marshal(dst.RefreshMentalModelOperationDetails)
		if string(jsonRefreshMentalModelOperationDetails) == "{}" { // empty struct
			dst.RefreshMentalModelOperationDetails = nil
		} else {
			if err = validator.Validate(dst.RefreshMentalModelOperationDetails); err != nil {
				dst.RefreshMentalModelOperationDetails = nil
			} else {
				match++
			}
		}
	} else {
		dst.RefreshMentalModelOperationDetails = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.FileConvertRetainOperationDetails = nil
		dst.RefreshMentalModelOperationDetails = nil

		return fmt.Errorf("data matches more than one schema in oneOf(OperationResponseDetails)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(OperationResponseDetails)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OperationResponseDetails) MarshalJSON() ([]byte, error) {
	if src.FileConvertRetainOperationDetails != nil {
		return json.Marshal(&src.FileConvertRetainOperationDetails)
	}

	if src.RefreshMentalModelOperationDetails != nil {
		return json.Marshal(&src.RefreshMentalModelOperationDetails)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OperationResponseDetails) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.FileConvertRetainOperationDetails != nil {
		return obj.FileConvertRetainOperationDetails
	}

	if obj.RefreshMentalModelOperationDetails != nil {
		return obj.RefreshMentalModelOperationDetails
	}

	// all schemas are nil
	return nil
}

type NullableOperationResponseDetails struct {
	value *OperationResponseDetails
	isSet bool
}

func (v NullableOperationResponseDetails) Get() *OperationResponseDetails {
	return v.value
}

func (v *NullableOperationResponseDetails) Set(val *OperationResponseDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationResponseDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationResponseDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationResponseDetails(val *OperationResponseDetails) *NullableOperationResponseDetails {
	return &NullableOperationResponseDetails{value: val, isSet: true}
}

func (v NullableOperationResponseDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationResponseDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


